version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=sistema
      - POSTGRES_PASSWORD=om315
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gcezarines@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "om315"
    ports:
      - "54321:80"
    depends_on:
      - postgres
